### ISSUE TITLE
Add shortcut, such as prepending ">" to allow rendering of site URLs, not just search google.

### ISSUE THREAD

**Issue by adammpkins** [yessGlory17/programmer-browser#10]
Add shortcut, such as prepending ">" to allow rendering of site URLs, not just search google.

**Comment by yessGlory17** [comment]
:+1:

**Comment by adammpkins** [comment]
This is especially important for viewing work that I'm doing. I need to be able to access sites not indexed by search engines, also localhost.

**Comment by yessGlory17** [comment]
I'll work on that in a moment. But I don't think I'll be able to get it before Sunday.

**Comment by yessGlory17** [comment]
If you want to solve this problem, I can include your solution in the project.

**Comment by adammpkins** [comment]
No rush. Just explaining why it's important. 

I'm not an electron developer or typescript, but I'd love to help. Trying to get acquainted with the stack, personally.

**Comment by yessGlory17** [comment]
I'm very happy that you wanted to help. You can make a CONTRIBUTE.md for this project if it pulls the first one. In this way, you can help other people to contribute to the project.

EXAMPLE: https://github.com/yessGlory17/nft-marketplace/blob/main/CONTRIBUTING.md

**Comment by burakkaraceylan** [comment]
@yessGlory17 I will take this if you want. I can finish it this weekend.

**Comment by adammpkins** [comment]
Submitted pull request [✅66](https://github.com/yessGlory17/programmer-browser/pull/66)

**Comment by yessGlory17** [comment]
thanks :clap: @adammpkins

**Comment by adammpkins** [comment]
Thanks for considering and merging. I'd love to chip in more where I can.
