### ISSUE TITLE
With multiple tabs open, bottom tab has no screen real estate to browse.

### ISSUE THREAD

**Issue by adammpkins** [yessGlory17/programmer-browser#13]
## Prerequisites

- [x ] Using npm
- [ x] Using an up-to-date [`main` branch]
- [x ] Using latest version of devtools. [Check the docs for how to update]
- [ x] Tried solutions mentioned in [#400]
- [ x] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Current Behavior
With 5+ tabs open, the bottom tab has no space for the browser. 

## Steps to Reproduce

1.Open 7 tabs

2.Open one more

3.No space to browse effectively

## Possible Solution (Not obligatory)
When a tab is expanded, it could temporarily shift into the top tab position, allowing the full height of the screen to be used for browsing regardless of tab position.

## Your Environment

- Node version :
- Operating System and version :

**Comment by yessGlory17** [comment]
:+1:

**Comment by yessGlory17** [comment]
I'm working on this issue.

**Comment by yessGlory17** [comment]
#30
