### ISSUE TITLE
Exception when using the move window left keyboard shortcut

### ISSUE THREAD

**Issue by adammpkins** [yessGlory17/programmer-browser#17]
## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch]
- [x] Using latest version of devtools. [Check the docs for how to update]
- [x] Tried solutions mentioned in [#400]
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior
When pressing ctrl+left, window should move

## Current Behavior
When ctrl+left is pressed, exception is thrown

![image](https://user-images.githubusercontent.com/1379536/170883020-68d7fb0b-f3db-4dc7-a022-3bd6dfb349a8.png)

## Steps to Reproduce

1.Open application

2.Press ctrl+left

3.Javascript exception "e.substr" is not a function is thrown

4.

## Your Environment

- Node version : 16.2.0
- Operating System and version : Ubuntu 20.04

**Comment by yessGlory17** [comment]
I fixed the error. I will publish my new version in an hour. #19
