### ISSUE TITLE
Alpha Features

### ISSUE THREAD

**Issue by yessGlory17** [yessGlory17/programmer-browser#2]
That is pretty slick. Looks like it is set by default to always be on top, which is awesome for its use case. Having a keyboard shortcut to trigger it would be a great addition, and being able to customize the window location would be really awesome too.

**Comment by vivek201** [comment]
The mouse back/forward buttons don't respond in this browser. That would be a great addition.

**Comment by yessGlory17** [comment]
I will take care of it. :+1:
