### ISSUE TITLE
typo in identifier: Positoner

### ISSUE THREAD

**Issue by hex13** [yessGlory17/programmer-browser#24]
There's a typo: 
Positoner instead of Positioner
https://github.com/yessGlory17/programmer-browser/blob/e2e4e3accef4364a10a8195ac358424c28b29d68/src/main/main.ts#L17

```javascript
import Positoner from 'electron-positioner';
// ...
positioner = new Positoner(mainWindow);
```

**Comment by yessGlory17** [comment]
version?

**Comment by hex13** [comment]
it's in current version of the repo on main branch.

**Comment by yessGlory17** [comment]
:+1:
