### ISSUE TITLE
ctr+f keyboard shortcut

### ISSUE THREAD

**Issue by adammpkins** [yessGlory17/programmer-browser#25]
Needs a ctr+f keyboard shortcut for finding text on the page.

**Comment by yessGlory17** [comment]
:+1:

**Comment by yessGlory17** [comment]
https://github.com/yessGlory17/programmer-browser/pull/62
![Screenshot from 2022-10-08 23-13-37](https://user-images.githubusercontent.com/52113663/194726438-7a3457ff-3056-4ab0-b6a6-447228b16ce4.png)
