### ISSUE TITLE
Merge broke current build. Button cannot appear as a descendant of button. Collapse not working.

### ISSUE THREAD

**Issue by adammpkins** [yessGlory17/programmer-browser#28]
## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch]
- [x] Using latest version of devtools. [Check the docs for how to update]
- [x] Tried solutions mentioned in [#400]
- [X] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

>  validateDOMNesting(...): <button> cannot appear as a descendant of <button>.
>     at button
>     at http://localhost:1212/renderer.dev.js:31985:66
>     at http://localhost:1212/renderer.dev.js:1761:15
>     at http://localhost:1212/renderer.dev.js:1864:20
>     at button
>     at http://localhost:1212/renderer.dev.js:31985:66
>     at http://localhost:1212/renderer.dev.js:526:32
>     at h2
>     at div
>     at http://localhost:1212/renderer.dev.js:31985:66
>     at http://localhost:1212/renderer.dev.js:463:24
>     at BrowserCollapse (http://localhost:1212/renderer.dev.js:107567:28)
>     at div
>     at http://localhost:1212/renderer.dev.js:31985:66
>     at http://localhost:1212/renderer.dev.js:410:23
>     at div
>     at List (http://localhost:1212/renderer.dev.js:107658:45)
>     at TabContextProvider (http://localhost:1212/renderer.dev.js:108034:31)
>     at div
>     at http://localhost:1212/renderer.dev.js:31985:66
>     at http://localhost:1212/renderer.dev.js:7993:94
>     at SearchContextProvider (http://localhost:1212/renderer.dev.js:107947:34)
>     at div
>     at Hello
>     at Routes (http://localhost:1212/renderer.dev.js:101831:5)
>     at Router (http://localhost:1212/renderer.dev.js:101765:15)
>     at MemoryRouter (http://localhost:1212/renderer.dev.js:101678:5)
>     at App
>     at EnvironmentProvider (http://localhost:1212/renderer.dev.js:14894:24)
>     at ColorModeProvider (http://localhost:1212/renderer.dev.js:3194:21)
>     at ThemeProvider (http://localhost:1212/renderer.dev.js:32024:64)
>     at ThemeProvider (http://localhost:1212/renderer.dev.js:20377:27)
>     at ChakraProvider (http://localhost:1212/renderer.dev.js:14194:24)
>     at ChakraProvider (http://localhost:1212/renderer.dev.js:15575:23)
> overrideMethod @ react_devtools_backend.js:4026
> printWarning @ react-dom.development.js:86
> error @ react-dom.development.js:60
> validateDOMNesting @ react-dom.development.js:10846
> createInstance @ react-dom.development.js:10927
> completeWork @ react-dom.development.js:19415
> completeUnitOfWork @ react-dom.development.js:26552
> performUnitOfWork @ react-dom.development.js:26524
> workLoopSync @ react-dom.development.js:26422
> renderRootSync @ react-dom.development.js:26390
> performSyncWorkOnRoot @ react-dom.development.js:26041
> flushSyncCallbacks @ react-dom.development.js:12009
> (anonymous) @ react-dom.development.js:25607
> 

## Expected Behavior

Tab throws error when search is executed. After that, the tab fails to collapse.

## Steps to Reproduce

1. Run app with DEBUG=true

2.execute a search

3. exception thrown

4.

## Your Environment

- Node version : 16.2.0
- Operating System and version : Ubuntu 20.04

**Comment by yessGlory17** [comment]
:+1:

**Comment by yessGlory17** [comment]
#30

**Comment by adammpkins** [comment]
This issue persists. Still getting 
Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.
    at button
    at http://localhost:1212/renderer.dev.js:31985:66
    at http://localhost:1212/renderer.dev.js:1761:15
    at http://localhost:1212/renderer.dev.js:1864:20
    at button
    at http://localhost:1212/renderer.dev.js:31985:66
    at http://localhost:1212/renderer.dev.js:526:32
    at h2
    at div
    at http://localhost:1212/renderer.dev.js:31985:66
    at http://localhost:1212/renderer.dev.js:463:24
    at BrowserCollapse (http://localhost:1212/renderer.dev.js:107567:28)
    at div
    at http://localhost:1212/renderer.dev.js:31985:66
    at http://localhost:1212/renderer.dev.js:410:23
    at div
    at List (http://localhost:1212/renderer.dev.js:107658:45)
    at TabContextProvider (http://localhost:1212/renderer.dev.js:108033:31)
    at div
    at http://localhost:1212/renderer.dev.js:31985:66
    at http://localhost:1212/renderer.dev.js:7993:94
    at SearchContextProvider (http://localhost:1212/renderer.dev.js:107946:34)
    at div
    at Hello
    at Routes (http://localhost:1212/renderer.dev.js:101831:5)
    at Router (http://localhost:1212/renderer.dev.js:101765:15)
    at MemoryRouter (http://localhost:1212/renderer.dev.js:101678:5)
    at App
    at EnvironmentProvider (http://localhost:1212/renderer.dev.js:14894:24)
    at ColorModeProvider (http://localhost:1212/renderer.dev.js:3194:21)
    at ThemeProvider (http://localhost:1212/renderer.dev.js:32024:64)
    at ThemeProvider (http://localhost:1212/renderer.dev.js:20377:27)
    at ChakraProvider (http://localhost:1212/renderer.dev.js:14194:24)
    at ChakraProvider (http://localhost:1212/renderer.dev.js:15575:23)



On current build. Just pulled and rebuilt.

**Comment by adammpkins** [comment]
Still cannot build a functional build on linux.

**Comment by yessGlory17** [comment]
https://github.com/yessGlory17/programmer-browser/pull/63
