### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by yessGlory17** [yessGlory17/programmer-browser#55]

**Comment by adammpkins** [comment]
This one might be easier to fulfill if you/we reconsider the naming/branding of this application. Programmer browser is great because it tells what the application does, but it's not very brandable. It'd be hard to iconize because programmer and browser don't have a lot of iconography aside from maybe globes for browsers, and dollar signs/hashes for programming.

Maybe something like DevSurf or LiteSurf, SideSurf or WebWing?

**Comment by adammpkins** [comment]
For the record, I have a designer here, and she's intrigued, but doesn't find the current name easily brandable.

**Comment by yessGlory17** [comment]
You are right about what you said. However, the name "programmer browser" is a name with high seo success. If you search for "programmer browser" on Google, it appears in the first place, even though it is given a star by so few people. My suggestion is to make a design using the letters P and B. We do not currently have a designer. If we have a good design and log for this application, I will contribute to this project every day.

**Comment by yessGlory17** [comment]
The new architecture of the project is ready. But its design and logo are still missing. If we can solve this problem, we can make rapid progress. People show interest in this project but refuse to support it because they don't find the logo and design professional enough.

**Comment by adammpkins** [comment]
Made a couple of quick mockups on a whim tonight. They can be  modified. I especially like the one with the purple background. https://imgur.com/a/xXcyxYW 

They're just mockups. They can be modified.

**Comment by yessGlory17** [comment]
awesome :tada:

**Comment by yessGlory17** [comment]
![Screenshot from 2023-02-03 13-36-06](https://user-images.githubusercontent.com/52113663/216579862-7c354d52-0d31-41a5-b551-29cc91e7c84a.png)
This is very beautiful

**Comment by adammpkins** [comment]
Thank you. I'd be happy to build the marketing site for it when you're ready for that too.

**Comment by yessGlory17** [comment]
Is it the landing page that you are trying to describe by saying a marketing site?

**Comment by adammpkins** [comment]
Yeah, like programmer-browser.github.io, or a custom domain or something. Something like this: https://obsidian.md/

**Comment by yessGlory17** [comment]
We can do Landing Page together. We can make a design similar to this https://vercel.com/

**Comment by adammpkins** [comment]
That is nearly EXACTLY the type of thing I was planning! I was hoping to make use of very slowly animated soft gradients. Let me know how you want to approach working on it together and I'm in.

**Comment by yessGlory17** [comment]
We can talk about it via email ozgurkurucan337@gmail.com

**Comment by adammpkins** [comment]
@yessGlory17 I have created Pull Request #71 to add the asset to the package and see how it looks.

**Comment by adammpkins** [comment]
![image](https://user-images.githubusercontent.com/1379536/220809465-ec5c6c81-356e-44f4-8666-999bd79b950c.png)
Looks pretty good to me. I've tested it on my Linux machine as well. Let me know what you think. I'd love to merge it in.

**Comment by yessGlory17** [comment]
#71 :tada:

**Comment by adammpkins** [comment]
> #71 tada

Thanks @yessGlory17  I also added another pull request for the icon in the documentation to have the gradient background for the logo so it's not white on white.
